### ISSUE TITLE
[Enhancement] Invalid type of send value in PATCH request on System's Boot object should return InvalidPayload.

### ISSUE THREAD

**Issue by ehaligow** [ODIM-Project/ODIM#598]
When invalid PATCH request (with invalid values) is send to System's Boot object, ODIM should return InvalidPayload. 

When invalid String is send, the InvalidPayload is returned. But, in case of boolean or int, GeneralError is returned.

![image](https://user-images.githubusercontent.com/13691077/125610472-ab1febd1-16cc-47a3-9a5b-17b2b2d86507.png)

**Comment by bharath-b-hpe** [comment]
Hello @ehaligow 

Thank you for the report.

Will have a look at it and get back with the analysis.

**Comment by bharath-b-hpe** [comment]
Hi @ehaligow 

Error response has been updated, instead of InternalError
- if request does not contain the value in expected type PropertyValueTypeError error will be indicated
- if request is not valid json MalformedJSON error will be indicated
- if request contains unsupported value for an attribute, error indicated by the device will be forwarded to the user.

Please let us know if any comments or the issue can be closed.

**Comment by ehaligow** [comment]
For me the issue can be closed :)
